# Generated by Django 3.0.4 on 2020-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=32)),
                ('stu_name', models.CharField(max_length=32, null=True)),
                ('stu_age', models.CharField(max_length=32)),
                ('weChat', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
