# Generated by Django 3.0.4 on 2020-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
