# Generated by Django 3.0.4 on 2020-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200827_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=64)),
                ('com_tel', models.CharField(max_length=32)),
                ('com_weChat', models.ImageField(upload_to='', verbose_name='官方微信')),
                ('com_validity', models.CharField(max_length=256)),
                ('com_introduction', models.TextField(verbose_name='公司详情')),
                ('teach_idea', models.TextField(verbose_name='教学理念')),
                ('school_address', models.TextField(verbose_name='校区分布')),
                ('recruit', models.TextField(verbose_name='招聘信息')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=32, unique=True)),
                ('com_validity', models.CharField(max_length=256)),
                ('com_introduction', models.ImageField(upload_to='', verbose_name='竞赛介绍')),
                ('com_result', models.ImageField(null=True, upload_to='', verbose_name='竞赛成绩')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour_name', models.CharField(max_length=32, unique=True)),
                ('cour_validity', models.CharField(max_length=256)),
                ('cour_introduction', models.ImageField(upload_to='', verbose_name='课程介绍')),
            ],
        ),
    ]
