# Generated by Django 3.0.4 on 2020-10-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_company_competition_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='com_result',
        ),
        migrations.AlterField(
            model_name='competition',
            name='com_introduction',
            field=models.TextField(verbose_name='竞赛介绍'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cour_introduction',
            field=models.TextField(verbose_name='课程介绍'),
        ),
    ]
