# Generated by Django 3.0.4 on 2020-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_order_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='com_log',
            field=models.ImageField(default=None, upload_to='', verbose_name='竞赛照片'),
            preserve_default=False,
        ),
    ]
