# Generated by Django 3.0.4 on 2020-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_competition_com_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='com_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='竞赛照片'),
        ),
    ]
