# Generated by Django 3.0.4 on 2020-10-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_course_cour_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(max_length=32)),
                ('sc_addr', models.CharField(max_length=256)),
                ('sc_tel', models.CharField(max_length=32)),
            ],
        ),
    ]
