# Generated by Django 3.0.4 on 2020-10-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_school_sc_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_name', models.CharField(max_length=64, unique=True)),
                ('cr_img', models.ImageField(null=True, upload_to='', verbose_name='竞赛照片')),
            ],
        ),
    ]
